#!/usr/bin/env bash
set -euo pipefail

# sync-zotero-bib.sh - Zotero Bibliography Git Sync Automation
#
# Purpose: Validate and commit Zotero BibTeX exports to git
# Usage: ./sync-zotero-bib.sh
# Frequency: Run before commits or weekly
#
# Features:
# - Validates BibTeX syntax (if bibtex-tidy installed)
# - Counts entries
# - Auto-commits to git if changes detected
# - Generates semantic commit messages
#
# Created: 2025-10-10
# Part of: KANNA Academic Tools Stack (Tier 2)

BIBTEX_FILE="$HOME/LAB/projects/KANNA/literature/zotero-export/kanna.bib"

echo "📚 Zotero Bibliography Sync"
echo "============================"
echo ""

# Check if BibTeX file exists
if [ ! -f "$BIBTEX_FILE" ]; then
  echo "❌ BibTeX file not found: $BIBTEX_FILE"
  echo ""
  echo "   Ensure Zotero auto-export is configured:"
  echo "   1. In Zotero: Right-click collection → Export Collection"
  echo "   2. Format: 'Better BibTeX'"
  echo "   3. ✅ Check 'Keep updated'"
  echo "   4. Save to: $BIBTEX_FILE"
  echo ""
  exit 1
fi

# Count entries
ENTRIES=$(grep -c "^@" "$BIBTEX_FILE" || echo "0")
FILE_SIZE=$(du -h "$BIBTEX_FILE" | cut -f1)
LAST_MODIFIED=$(stat -c %y "$BIBTEX_FILE" | cut -d'.' -f1)

echo "📊 Bibliography Statistics:"
echo "   - Entries: $ENTRIES"
echo "   - File size: $FILE_SIZE"
echo "   - Last modified: $LAST_MODIFIED"
echo ""

# Validate expected entry count
if [ "$ENTRIES" -lt 100 ]; then
  echo "⚠️  Warning: Expected ~142 entries, found $ENTRIES"
  echo "   Ensure Zotero PDF import is complete"
  echo ""
fi

# Validate BibTeX syntax (if bibtex-tidy available)
if command -v bibtex-tidy &> /dev/null; then
  echo "🔍 Validating BibTeX syntax..."
  if bibtex-tidy --check "$BIBTEX_FILE" 2>&1 | head -10; then
    echo "✅ BibTeX syntax valid"
  else
    echo "⚠️  BibTeX validation warnings (see above)"
    echo "   Common issues: missing commas, unescaped characters"
  fi
  echo ""
else
  echo "ℹ️  bibtex-tidy not installed (optional validation)"
  echo "   Install with: npm install -g bibtex-tidy"
  echo ""
fi

# Check for duplicate citation keys (common error)
DUPLICATE_KEYS=$(grep "^@" "$BIBTEX_FILE" | \
  awk -F'{' '{print $2}' | \
  awk -F',' '{print $1}' | \
  sort | uniq -d)

if [ -n "$DUPLICATE_KEYS" ]; then
  echo "⚠️  Duplicate citation keys found:"
  echo "$DUPLICATE_KEYS" | while read -r key; do
    echo "   - $key"
  done
  echo "   Fix in Zotero: Tools → Better BibTeX → Preferences → Citation keys"
  echo ""
fi

# Git operations
cd ~/LAB/projects/KANNA

echo "📝 Git Status:"
if git diff --quiet literature/zotero-export/kanna.bib 2>/dev/null; then
  echo "   No changes to commit"
  echo ""
  echo "✅ Bibliography is up-to-date with git"
  exit 0
else
  # Calculate diff statistics
  ADDED=$(git diff literature/zotero-export/kanna.bib | grep -c "^+" || echo "0")
  REMOVED=$(git diff literature/zotero-export/kanna.bib | grep -c "^-" || echo "0")

  echo "   Changes detected:"
  echo "   - Added lines: $ADDED"
  echo "   - Removed lines: $REMOVED"
  echo ""

  # Show entry count change
  PREV_ENTRIES=$(git show HEAD:literature/zotero-export/kanna.bib 2>/dev/null | grep -c "^@" || echo "unknown")
  if [ "$PREV_ENTRIES" != "unknown" ]; then
    ENTRY_DIFF=$((ENTRIES - PREV_ENTRIES))
    if [ $ENTRY_DIFF -gt 0 ]; then
      echo "   📈 Added $ENTRY_DIFF entries"
    elif [ $ENTRY_DIFF -lt 0 ]; then
      echo "   📉 Removed ${ENTRY_DIFF#-} entries"
    else
      echo "   📝 Updated metadata (same entry count)"
    fi
  fi
  echo ""

  # Commit changes
  git add literature/zotero-export/kanna.bib

  # Generate semantic commit message
  COMMIT_MSG="data: update Zotero bibliography ($ENTRIES entries)

Updated bibliography with latest paper metadata from Zotero.

Statistics:
- Total entries: $ENTRIES
- File size: $FILE_SIZE
- Auto-synced: $(date +'%Y-%m-%d %H:%M')

Auto-generated by tools/scripts/sync-zotero-bib.sh"

  git commit -m "$COMMIT_MSG"

  echo "✅ Bibliography committed to git"
  echo "   Commit message: \"data: update Zotero bibliography ($ENTRIES entries)\""
  echo ""
fi

# Summary
echo "📋 Next Steps:"
echo "   1. Review changes: git log -1 --stat"
echo "   2. Push to remote: git push (if needed)"
echo "   3. Update VOSviewer analysis: ./tools/scripts/analyze-citation-network.sh"
echo ""
echo "✅ Sync complete!"

exit 0
