name: ml-stack
channels:
- conda-forge
- bioconda
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- alsa-lib=1.2.14
- annotated-types=0.7.0
- anyio=4.11.0
- aom=3.9.1
- argon2-cffi-bindings=25.1.0
- argon2-cffi=25.1.0
- arrow=1.3.0
- astroid=3.3.11
- asttokens=3.0.0
- async-lru=2.0.5
- attrs=25.4.0
- autopep8=2.0.4
- babel=2.17.0
- beautifulsoup4=4.14.2
- biopython=1.85
- black=25.1.0
- bleach-with-css=6.2.0
- bleach=6.2.0
- blosc=1.21.6
- brotli-bin=1.1.0
- brotli-python=1.1.0
- brotli=1.1.0
- brunsli=0.1
- bzip2=1.0.8
- c-ares=1.34.5
- c-blosc2=2.21.2
- ca-certificates=2025.10.5
- cached-property=1.5.2
- cached_property=1.5.2
- cairo=1.18.4
- catalogue=2.0.10
- certifi=2025.10.5
- cffi=2.0.0
- cfgv=3.3.1
- charls=2.4.2
- charset-normalizer=3.4.3
- click=8.3.0
- cloudpathlib=0.22.0
- cloudpickle=3.1.1
- cmake=4.1.1
- colorama=0.4.6
- comm=0.2.3
- confection=0.1.5
- contourpy=1.3.3
- cuda-version=12.9
- cycler=0.12.1
- cymem=2.0.11
- cyrus-sasl=2.1.28
- cython-blis=1.3.0
- dav1d=1.2.1
- dbus=1.16.2
- debugpy=1.8.17
- decorator=5.2.1
- defusedxml=0.7.1
- dill=0.4.0
- distlib=0.4.0
- docstring-to-markdown=0.17
- double-conversion=3.3.1
- exceptiongroup=1.3.0
- executing=2.2.1
- flake8=7.1.2
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.15.0
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.60.1
- fqdn=1.5.1
- freetype-py=2.3.0
- freetype=2.14.1
- giflib=5.2.2
- git=2.51.0
- graphite2=1.3.14
- greenlet=3.2.4
- h11=0.16.0
- h2=4.3.0
- harfbuzz=12.1.0
- hpack=4.1.0
- httpcore=1.0.9
- httpx=0.28.1
- hyperframe=6.1.0
- icu=75.1
- identify=2.6.14
- idna=3.10
- imagecodecs=2025.8.2
- imageio=2.37.0
- importlib-metadata=8.7.0
- ipykernel=6.30.1
- ipython=9.6.0
- ipython_pygments_lexers=1.1.1
- ipywidgets=8.1.7
- iqtree=3.0.1
- isoduration=20.11.0
- isort=6.0.1
- jedi=0.19.2
- jinja2=3.1.6
- joblib=1.5.2
- json5=0.12.1
- jsonpointer=3.0.0
- jsonschema-specifications=2025.9.1
- jsonschema-with-format-nongpl=4.25.1
- jsonschema=4.25.1
- jupyter-lsp=2.3.0
- jupyter=1.1.1
- jupyter_client=8.6.3
- jupyter_console=6.6.3
- jupyter_core=5.8.1
- jupyter_events=0.12.0
- jupyter_server=2.17.0
- jupyter_server_terminals=0.5.3
- jupyterlab-lsp=5.2.0
- jupyterlab=4.4.9
- jupyterlab_pygments=0.3.0
- jupyterlab_server=2.27.3
- jupyterlab_widgets=3.0.15
- jxrlib=1.1
- keyutils=1.6.3
- kiwisolver=1.4.9
- krb5=1.21.3
- langcodes=3.4.1
- language-data=1.3.0
- lark=1.2.2
- lazy-loader=0.4
- lcms2=2.17
- ld_impl_linux-64=2.44
- lerc=4.0.0
- libaec=1.1.4
- libavif16=1.3.0
- libblas=3.9.0
- libboost-python=1.86.0
- libboost=1.86.0
- libbrotlicommon=1.1.0
- libbrotlidec=1.1.0
- libbrotlienc=1.1.0
- libcblas=3.9.0
- libclang-cpp21.1=21.1.2
- libclang13=21.1.2
- libcups=2.3.3
- libcurl=8.14.1
- libdeflate=1.24
- libdrm=2.4.125
- libedit=3.1.20250104
- libegl=1.7.0
- libev=4.33
- libexpat=2.7.1
- libffi=3.4.6
- libfreetype6=2.14.1
- libfreetype=2.14.1
- libgcc-ng=15.2.0
- libgcc=15.2.0
- libgfortran5=15.2.0
- libgfortran=15.2.0
- libgl=1.7.0
- libglib=2.86.0
- libglvnd=1.7.0
- libglx=1.7.0
- libgomp=15.2.0
- libhwy=1.3.0
- libiconv=1.18
- libjpeg-turbo=3.1.0
- libjxl=0.11.1
- liblapack=3.9.0
- libllvm21=21.1.3
- liblzma=5.8.1
- libnghttp2=1.67.0
- libnsl=2.0.1
- libntlm=1.8
- libopenblas=0.3.30
- libopengl=1.7.0
- libpciaccess=0.18
- libpng=1.6.50
- libpq=18.0
- librdkit=2025.09.1
- libsodium=1.0.20
- libsqlite=3.50.4
- libssh2=1.11.1
- libstdcxx-ng=15.2.0
- libstdcxx=15.2.0
- libtiff=4.7.1
- libuuid=2.41.2
- libuv=1.51.0
- libvulkan-loader=1.4.328.0
- libwebp-base=1.6.0
- libxcb=1.17.0
- libxcrypt=4.4.36
- libxgboost=3.0.5
- libxkbcommon=1.11.0
- libxml2-16=2.15.0
- libxml2=2.15.0
- libxslt=1.1.43
- libzlib=1.3.1
- libzopfli=1.0.3
- lxml=6.0.2
- lz4-c=1.10.0
- marisa-trie=1.2.1
- markdown-it-py=4.0.0
- markupsafe=3.0.3
- matplotlib-base=3.10.6
- matplotlib-inline=0.1.7
- matplotlib=3.10.6
- mccabe=0.7.0
- mdurl=0.1.2
- mistune=3.1.4
- munkres=1.1.4
- murmurhash=1.0.13
- mypy_extensions=1.1.0
- nbclient=0.10.2
- nbconvert-core=7.16.6
- nbconvert-pandoc=7.16.6
- nbconvert=7.16.6
- nbformat=5.10.4
- nccl=2.27.7.1
- ncurses=6.5
- nest-asyncio=1.6.0
- nltk=3.9.2
- nodeenv=1.9.1
- notebook-shim=0.2.4
- notebook=7.4.7
- numpy=2.2.6
- openjpeg=2.5.4
- openldap=2.6.10
- openssl=3.5.4
- overrides=7.7.0
- packaging=25.0
- pandas=2.3.2
- pandoc=3.8
- pandocfilters=1.5.0
- parso=0.8.5
- pathspec=0.12.1
- patsy=1.0.1
- pcre2=10.46
- perl=5.32.1
- pexpect=4.9.0
- pickleshare=0.7.5
- pillow=11.3.0
- pip
- pip=25.2
- pixman=0.46.4
- platformdirs=4.4.0
- pluggy=1.6.0
- pre-commit=4.3.0
- preshed=3.0.9
- prometheus_client=0.23.1
- prompt-toolkit=3.0.52
- prompt_toolkit=3.0.52
- psutil=7.1.0
- pthread-stubs=0.4
- ptyprocess=0.7.0
- pure_eval=0.2.3
- py-xgboost=3.0.5
- pycairo=1.28.0
- pycodestyle=2.12.1
- pycparser=2.22
- pydantic-core=2.41.1
- pydantic=2.12.0
- pydocstyle=6.3.0
- pyflakes=3.2.0
- pygments=2.19.2
- pylint=3.3.8
- pyparsing=3.2.5
- pyside6=6.9.3
- pysocks=1.7.1
- python-dateutil=2.9.0.post0
- python-fastjsonschema=2.21.2
- python-json-logger=2.0.7
- python-lsp-jsonrpc=1.1.2
- python-lsp-server-base=1.13.1
- python-lsp-server=1.13.1
- python-tzdata=2025.2
- python=3.11.13
- python_abi=3.11
- pytoolconfig=1.2.5
- pytz=2025.2
- pywavelets=1.9.0
- pyyaml=6.0.3
- pyzmq=27.1.0
- qhull=2020.2
- qt6-main=6.9.3
- rav1e=0.7.1
- rdkit=2025.09.1
- readline=8.2
- referencing=0.36.2
- regex=2025.9.18
- reportlab=4.4.4
- requests=2.32.5
- rfc3339-validator=0.1.4
- rfc3986-validator=0.1.1
- rfc3987-syntax=1.1.0
- rhash=1.4.6
- rich=14.1.0
- rlpycairo=0.4.0
- rope=1.14.0
- rpds-py=0.27.1
- ruff=0.13.1
- scikit-image=0.25.2
- scikit-learn=1.7.2
- scipy=1.16.2
- seaborn-base=0.13.2
- seaborn=0.13.2
- send2trash=1.8.3
- setuptools=80.9.0
- shellingham=1.5.4
- six=1.17.0
- smart-open=7.3.1
- smart_open=7.3.1
- snappy=1.2.2
- sniffio=1.3.1
- snowballstemmer=3.0.1
- soupsieve=2.8
- spacy-legacy=3.0.12
- spacy-loggers=1.0.5
- spacy=3.8.7
- sqlalchemy=2.0.43
- srsly=2.5.1
- stack_data=0.6.3
- statsmodels=0.14.5
- svt-av1=3.1.2
- terminado=0.18.1
- thinc=8.3.6
- threadpoolctl=3.6.0
- tifffile=2025.9.9
- tinycss2=1.4.0
- tk=8.6.13
- tomli=2.2.1
- tomlkit=0.13.3
- tornado=6.5.2
- tqdm=4.67.1
- traitlets=5.14.3
- typer-slim-standard=0.19.2
- typer-slim=0.19.2
- typer=0.19.2
- types-python-dateutil=2.9.0.20251008
- typing-extensions=4.15.0
- typing-inspection=0.4.2
- typing_extensions=4.15.0
- typing_utils=0.1.0
- tzdata=2025b
- ujson=5.11.0
- ukkonen=1.0.1
- unicodedata2=16.0.0
- uri-template=1.3.0
- urllib3=2.5.0
- virtualenv=20.34.0
- wasabi=1.1.3
- wayland=1.24.0
- wcwidth=0.2.14
- weasel=0.4.1
- webcolors=24.11.1
- webencodings=0.5.1
- websocket-client=1.8.0
- whatthepatch=1.0.7
- wheel=0.45.1
- widgetsnbextension=4.0.14
- wrapt=1.17.3
- xcb-util-cursor=0.1.5
- xcb-util-image=0.4.0
- xcb-util-keysyms=0.4.1
- xcb-util-renderutil=0.3.10
- xcb-util-wm=0.4.2
- xcb-util=0.4.1
- xgboost=3.0.5
- xkeyboard-config=2.46
- xorg-libice=1.1.2
- xorg-libsm=1.2.6
- xorg-libx11=1.8.12
- xorg-libxau=1.0.12
- xorg-libxcomposite=0.4.6
- xorg-libxcursor=1.2.3
- xorg-libxdamage=1.1.6
- xorg-libxdmcp=1.1.5
- xorg-libxext=1.3.6
- xorg-libxfixes=6.0.2
- xorg-libxi=1.8.2
- xorg-libxrandr=1.5.4
- xorg-libxrender=0.9.12
- xorg-libxtst=1.2.5
- xorg-libxxf86vm=1.1.6
- yaml=0.2.5
- yapf=0.43.0
- zeromq=4.3.5
- zfp=1.0.1
- zipp=3.23.0
- zlib-ng=2.2.5
- zstandard=0.25.0
- zstd=1.5.7
- pip:
  - torch==2.8.0+cu128
  - torchvision==0.23.0+cu128
  - torchaudio==2.8.0+cu128
- pip:
  - flash-attn==2.8.3
  - absl-py==2.3.1
  - aiohappyeyeballs==2.6.1
  - aiohttp==3.13.0
  - aiosignal==1.4.0
  - aiosqlite==0.21.0
  - array-record==0.8.1
  - astor==0.8.1
  - astunparse==1.6.3
  - async-timeout==4.0.3
  - auto-gptq==0.7.1
  - autoawq==0.2.9
  - backoff==2.2.1
  - banks==2.2.0
  - bcrypt==5.0.0
  - bitsandbytes==0.47.0
  - blake3==1.0.7
  - build==1.3.0
  - cachetools==6.2.0
  - cattrs==25.3.0
  - cbor2==5.7.0
  - chembl-webresource-client==0.10.9
  - cheroot==10.0.1
  - chromadb==1.1.1
  - coloredlogs==15.0.1
  - compressed-tensors==0.11.0
  - cupy-cuda12x==13.6.0
  - dataclasses-json==0.6.7
  - datasets==4.1.1
  - deprecated==1.2.18
  - depyf==0.19.0
  - dirtyjson==1.0.8
  - diskcache==5.6.3
  - distro==1.9.0
  - dm-tree==0.1.9
  - dnspython==2.8.0
  - docstring-parser==0.17.0
  - durationpy==0.10
  - easydict==1.13
  - einops==0.8.1
  - email-validator==2.3.0
  - etils==1.13.0
  - fastapi==0.118.1
  - fastapi-cli==0.0.13
  - fastapi-cloud-cli==0.3.0
  - fastrlock==0.8.3
  - filelock==3.19.1
  - filetype==1.2.0
  - flatbuffers==25.9.23
  - frozendict==2.4.6
  - frozenlist==1.8.0
  - fsspec==2025.9.0
  - gast==0.6.0
  - gcsfs==2025.9.0
  - gekko==1.3.0
  - gguf==0.17.1
  - gitdb==4.0.12
  - gitpython==3.1.45
  - google-api-core==2.25.1
  - google-auth==2.41.1
  - google-auth-oauthlib==1.2.2
  - google-cloud-core==2.4.3
  - google-cloud-storage==3.4.0
  - google-crc32c==1.7.1
  - google-pasta==0.2.0
  - google-resumable-media==2.7.2
  - googleapis-common-protos==1.70.0
  - griffe==1.14.0
  - grpcio==1.75.1
  - gviz-api==1.10.0
  - h5py==3.14.0
  - hf-xet==1.1.10
  - httptools==0.6.4
  - httpx-sse==0.4.2
  - huggingface-hub==0.35.3
  - humanfriendly==10.0
  - immutabledict==4.2.1
  - importlib-resources==6.5.2
  - interegular==0.3.3
  - jaraco-functools==4.3.0
  - jiter==0.11.0
  - jsonpatch==1.33
  - jupyter-collaboration==4.1.1
  - jupyter-collaboration-ui==2.1.1
  - jupyter-docprovider==2.1.1
  - jupyter-resource-usage==1.2.0
  - jupyter-server-fileid==0.9.3
  - jupyter-server-mathjax==0.2.6
  - jupyter-server-proxy==4.4.0
  - jupyter-server-ydoc==2.1.1
  - jupyter-ydoc==3.1.0
  - jupyterlab-code-formatter==3.0.2
  - jupyterlab-execute-time==3.2.0
  - jupyterlab-git==0.51.2
  - jupyterlab-nvdashboard==0.13.0
  - jupyterlab-widgets==3.0.15
  - kagglehub==0.3.13
  - keras==3.11.3
  - keras-hub==0.22.2
  - keras-nlp==0.22.2
  - kubernetes==34.1.0
  - langchain==0.3.27
  - langchain-community==0.3.31
  - langchain-core==0.3.78
  - langchain-openai==0.3.35
  - langchain-text-splitters==0.3.11
  - langsmith==0.4.33
  - lckr-jupyterlab-variableinspector==3.2.4
  - libclang==18.1.1
  - llama-cloud==0.1.35
  - llama-cloud-services==0.6.54
  - llama-index==0.14.4
  - llama-index-cli==0.5.3
  - llama-index-core==0.14.4
  - llama-index-embeddings-huggingface==0.6.1
  - llama-index-embeddings-openai==0.5.1
  - llama-index-indices-managed-llama-cloud==0.9.4
  - llama-index-instrumentation==0.4.1
  - llama-index-llms-openai==0.6.4
  - llama-index-readers-file==0.5.4
  - llama-index-readers-llama-parse==0.5.1
  - llama-index-workflows==2.6.0
  - llama-parse==0.6.54
  - llguidance==0.7.30
  - llvmlite==0.44.0
  - lm-format-enforcer==0.11.3
  - lsprotocol==2023.0.1
  - markdown==3.9
  - marshmallow==3.26.1
  - mistral-common==1.8.5
  - ml-dtypes==0.5.3
  - mmh3==5.2.0
  - mpmath==1.3.0
  - msgpack==1.1.2
  - msgspec==0.19.0
  - multidict==6.7.0
  - multiprocess==0.70.16
  - mypy-extensions==1.1.0
  - namex==0.1.0
  - nbdime==4.0.2
  - nbstripout==0.8.1
  - networkx==3.4.2
  - ninja==1.13.0
  - numba==0.61.2
  - nvidia-cublas==13.0.2.14
  - nvidia-cublas-cu12==12.8.4.1
  - nvidia-cuda-cupti-cu12==12.8.90
  - nvidia-cuda-nvrtc-cu12==12.8.93
  - nvidia-cuda-runtime-cu12==12.8.90
  - nvidia-cuda-runtime-cu13==0.0.0a0
  - nvidia-cudnn-cu12==9.10.2.21
  - nvidia-cudnn-cu13==9.13.1.26
  - nvidia-cufft-cu12==11.3.3.83
  - nvidia-cufile-cu12==1.13.1.3
  - nvidia-curand-cu12==10.3.9.90
  - nvidia-cusolver-cu12==11.7.3.90
  - nvidia-cusparse-cu12==12.5.8.93
  - nvidia-cusparselt-cu12==0.7.1
  - nvidia-ml-py==12.575.51
  - nvidia-nccl-cu12==2.27.3
  - nvidia-nvjitlink-cu12==12.8.93
  - nvidia-nvtx-cu12==12.8.90
  - oauthlib==3.3.1
  - onnxruntime==1.23.1
  - openai==1.109.1
  - openai-harmony==0.0.4
  - opencv-python-headless==4.12.0.88
  - opentelemetry-api==1.37.0
  - opentelemetry-exporter-otlp-proto-common==1.37.0
  - opentelemetry-exporter-otlp-proto-grpc==1.37.0
  - opentelemetry-proto==1.37.0
  - opentelemetry-sdk==1.37.0
  - opentelemetry-semantic-conventions==0.58b0
  - opt-einsum==3.4.0
  - optimum==1.27.0
  - optree==0.17.0
  - orjson==3.11.3
  - outlines-core==0.2.11
  - partial-json-parser==0.2.1.1.post6
  - peft==0.17.1
  - posthog==5.4.0
  - prometheus-fastapi-instrumentator==7.1.0
  - promise==2.3
  - propcache==0.4.0
  - proto-plus==1.26.1
  - protobuf==5.29.5
  - pubchempy==1.0.5
  - py-cpuinfo==9.0.0
  - pyarrow==21.0.0
  - pyasn1==0.6.1
  - pyasn1-modules==0.4.2
  - pybase64==1.4.2
  - pycountry==24.6.1
  - pycrdt==0.12.37
  - pycrdt-store==0.1.2
  - pycrdt-websocket==0.16.0
  - pydantic-extra-types==2.10.5
  - pydantic-settings==2.11.0
  - pygls==1.3.1
  - pynvml==12.0.0
  - pypdf==6.1.1
  - pypika==0.48.9
  - pyproject-hooks==1.2.0
  - pyright==1.1.405
  - python-dotenv==1.1.1
  - python-multipart==0.0.20
  - pytokens==0.1.10
  - ray==2.49.2
  - requests-cache==1.2.1
  - requests-oauthlib==2.0.0
  - requests-toolbelt==1.0.0
  - rich-toolkit==0.15.1
  - rignore==0.7.0
  - rouge==1.0.1
  - rsa==4.9.1
  - ruff-lsp==0.0.62
  - safetensors==0.6.2
  - sentence-transformers==5.1.1
  - sentencepiece==0.2.1
  - sentry-sdk==2.40.0
  - setproctitle==1.3.7
  - shap==0.48.0
  - simpervisor==1.0.0
  - simple-parsing==0.1.7
  - slicer==0.0.8
  - smmap==5.0.2
  - soundfile==0.13.1
  - soxr==1.0.0
  - sqlite-anyio==0.2.3
  - starlette==0.48.0
  - striprtf==0.0.26
  - sympy==1.14.0
  - tenacity==9.1.2
  - tensorboard==2.19.0
  - tensorboard-data-server==0.7.2
  - tensorboard-plugin-profile==2.20.6
  - tensorflow==2.19.1
  - tensorflow-datasets==4.9.9
  - tensorflow-hub==0.16.1
  - tensorflow-io-gcs-filesystem==0.37.1
  - tensorflow-metadata==1.17.2
  - tensorflow-text==2.19.0
  - tensorrt-cu13==10.13.3.9
  - tensorrt-cu13-bindings==10.13.3.9
  - tensorrt-cu13-libs==10.13.3.9
  - termcolor==3.1.0
  - tf-keras==2.19.0
  - tiktoken==0.12.0
  - tokenizers==0.22.1
  - toml==0.10.2
  - transformers==4.57.0
  - triton==3.4.0
  - typing-inspect==0.9.0
  - url-normalize==2.2.1
  - uvicorn==0.37.0
  - uvloop==0.21.0
  - vllm==0.11.0
  - watchfiles==1.1.0
  - websockets==15.0.1
  - werkzeug==3.1.3
  - xformers==0.0.32.post1
  - xgrammar==0.1.25
  - xprof==2.20.6
  - xxhash==3.5.0
  - yarl==1.22.0
